definitions:
  auth.LoginInput:
    properties:
      email_or_username:
        type: string
      password:
        type: string
    required:
    - email_or_username
    - password
    type: object
  auth.RegisterInput:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
  chat.Room:
    properties:
      name:
        type: string
    type: object
  swg.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  swg.SuccessResponse:
    properties:
      message:
        type: string
    type: object
  swg.TokenResponse:
    properties:
      token:
        type: string
    type: object
  ws.Message:
    properties:
      content:
        type: string
    type: object
info:
  contact: {}
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Производит авторизацию пользователя по имени пользователя и паролю,
        возвращая токен для доступа
      parameters:
      - description: Данные для входа
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/auth.LoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: Токен доступа
          schema:
            $ref: '#/definitions/swg.TokenResponse'
        "401":
          description: Неверные данные для входа
          schema:
            $ref: '#/definitions/swg.ErrorResponse'
        "500":
          description: Ошибка генерации токена
          schema:
            $ref: '#/definitions/swg.ErrorResponse'
      summary: Авторизация пользователя
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Регистрирует нового пользователя с указанием имени и пароля
      parameters:
      - description: Данные пользователя
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/auth.RegisterInput'
      produces:
      - application/json
      responses:
        "201":
          description: Пользователь успешно зарегистрирован
          schema:
            $ref: '#/definitions/swg.SuccessResponse'
        "409":
          description: Имя пользователя или почта уже используется
          schema:
            $ref: '#/definitions/swg.ErrorResponse'
        "500":
          description: Ошибка хеширования или создания пользователя
          schema:
            $ref: '#/definitions/swg.ErrorResponse'
      summary: Регистрация нового пользователя
      tags:
      - auth
  /rooms:
    get:
      consumes:
      - application/json
      description: Получения списка доступных комнат после авторизации
      produces:
      - application/json
      responses:
        "200":
          description: Список комнат
          schema:
            items:
              $ref: '#/definitions/chat.Room'
            type: array
        "401":
          description: Требуется авторизация
          schema:
            $ref: '#/definitions/swg.ErrorResponse'
        "500":
          description: Не удалось получить список комнат
          schema:
            $ref: '#/definitions/swg.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Получения списка комнат
      tags:
      - rooms
    post:
      consumes:
      - application/json
      description: Создаёт комнату для подключения пользователей
      parameters:
      - description: Данные комнаты
        in: body
        name: room
        required: true
        schema:
          $ref: '#/definitions/chat.Room'
      produces:
      - application/json
      responses:
        "201":
          description: Созданная комната
          schema:
            $ref: '#/definitions/chat.Room'
        "401":
          description: Неверный токен
          schema:
            $ref: '#/definitions/swg.ErrorResponse'
        "409":
          description: Комната с таким названием уже существует
          schema:
            $ref: '#/definitions/swg.ErrorResponse'
        "500":
          description: Не удалось создать комнату
          schema:
            $ref: '#/definitions/swg.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Создание комнаты
      tags:
      - rooms
  /rooms/{room_id}/messages:
    get:
      consumes:
      - application/json
      description: Получения истории чата комнаты после авторизации
      parameters:
      - description: ID комнаты
        in: path
        name: room_id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Получения истории чата комнаты
      tags:
      - rooms
  /ws/{room_id}:
    get:
      consumes:
      - application/json
      description: Устанавливает WebSocket-соединение с указанной комнатой. Используйте
        ws:// или wss:// для подключения.
      parameters:
      - description: Сообщение
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/ws.Message'
      - description: ID комнаты
        in: path
        name: room_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "400":
          description: Неверный ID комнаты
          schema:
            $ref: '#/definitions/swg.ErrorResponse'
        "409":
          description: Не удалось найти пользователя
          schema:
            $ref: '#/definitions/swg.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Подключение к комнате
      tags:
      - ws
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
