definitions:
  auth.LoginInput:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  notes.Note:
    type: object
info:
  contact: {}
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Производит авторизацию пользователя по имени пользователя и паролю,
        возвращая токен для доступа
      parameters:
      - description: Данные для входа
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/auth.LoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: Токен доступа
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Ошибка валидации данных
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Неправильный логин или пароль
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Авторизация пользователя
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Регистрирует нового пользователя с указанием имени и пароля
      parameters:
      - description: Данные пользователя
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/auth.LoginInput'
      produces:
      - application/json
      responses:
        "201":
          description: Успешная регистрация
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Ошибка валидации
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Регистрация нового пользователя
      tags:
      - auth
  /notes:
    get:
      consumes:
      - application/json
      description: Возвращает все заметки текущего пользователя с возможностью фильтрации
      parameters:
      - description: Поиск по названию или описанию
        in: query
        name: search
        type: string
      - description: Начальная дата в формате YYYY-MM-DD
        in: query
        name: start
        type: string
      - description: Конечная дата в формате YYYY-MM-DD
        in: query
        name: end
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Список заметок
          schema:
            items:
              $ref: '#/definitions/notes.Note'
            type: array
        "401":
          description: Неавторизованный запрос
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Получение списка заметок
      tags:
      - notes
    post:
      consumes:
      - application/json
      description: Создает новую заметку для текущего пользователя
      parameters:
      - description: Данные заметки
        in: body
        name: note
        required: true
        schema:
          $ref: '#/definitions/notes.Note'
      produces:
      - application/json
      responses:
        "200":
          description: Создана новая заметка
          schema:
            $ref: '#/definitions/notes.Note'
        "400":
          description: Ошибка валидации данных
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Неавторизованный запрос
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Создание новой заметки
      tags:
      - notes
  /notes/{id}:
    delete:
      consumes:
      - application/json
      description: Удаляет заметку для текущего пользователя
      parameters:
      - description: ID заметки
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Сообщение об удалении
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Неавторизованный запрос
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Заметка не найдена
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Удаление заметки по ID
      tags:
      - notes
    get:
      consumes:
      - application/json
      description: Возвращает заметку по ID для текущего пользователя
      parameters:
      - description: ID заметки
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Заметка
          schema:
            $ref: '#/definitions/notes.Note'
        "401":
          description: Неавторизованный запрос
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Заметка не найдена
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Получение заметки по ID
      tags:
      - notes
    put:
      consumes:
      - application/json
      description: Обновляет данные заметки для текущего пользователя
      parameters:
      - description: ID заметки
        in: path
        name: id
        required: true
        type: integer
      - description: Данные для обновления
        in: body
        name: note
        required: true
        schema:
          $ref: '#/definitions/notes.Note'
      produces:
      - application/json
      responses:
        "200":
          description: Обновленная заметка
          schema:
            $ref: '#/definitions/notes.Note'
        "400":
          description: Ошибка валидации данных
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Неавторизованный запрос
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: Нет доступа
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Заметка не найдена
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Обновление заметки по ID
      tags:
      - notes
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
